### ISSUE TITLE
Newbie Help

### ISSUE THREAD

**Issue by mada949** [Jon2Anderson/NBA_Prediction_Modeling#1]
Hi Jon,

I'm new to Python and wanted to play around with your modeling.  Can you explain how to replace the "Home/JonAnderson" paths so that it works properly?

Thank you!

**Comment by Jon2Anderson** [comment]
Hey what’s up man. Sorry I just hosted my code there for my own purposes, it’s not really set up for people to grab and use. There are just a lot of file locations that you would have to change to fit your own needs if you’re copying my code.. but there’s also some other files and stuff that aren’t posted.

That’s what the /home/jon2anderson part is - just a file location for saving and loading

**Comment by mada949** [comment]
Ok, sorry! It has so much explanation, I thought it was for the public. Thanks!
